name: Auto-Release on Commit

on:
  push:
    branches: [ main ] 

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT
        
      - name: Get short SHA
        id: sha
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name: Delete existing 'latest' tag if it exists
        run: |
          git push origin :refs/tags/latest || true
        continue-on-error: true
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ steps.date.outputs.DATE }}-${{ steps.sha.outputs.SHA }}
          name: Auto Release ${{ steps.date.outputs.DATE }} (${{ steps.sha.outputs.SHA }})
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add 'latest' tag
        run: |
          git tag -f latest
          git push -f origin latest
